### ISSUE TITLE
萌新学习STL中,找到了大佬您的文章,但是好像被设置为私密了,大佬可以私发一份文章吗

### ISSUE THREAD

**Issue by KSroido** [Puppas/STL-in-Cpp11#1]
感觉大佬您写的非常通俗易懂!
https://www.jianshu.com/p/df1a059636a3
但是链接已经失效了,虽然不知道是什么原因
晚辈恳请大佬私发一下新的有效地址
有偿也行!!!
非常感谢呜呜呜
qq 1050452117
email ksxmyqj@gmail.com

**Comment by Puppas** [comment]
现在应该已经好了，谢谢支持

**Comment by KSroido** [comment]
感谢大佬的帮助!
